### ISSUE TITLE
Graph preview stops updating after editing

### ISSUE THREAD

**Issue by wassfila** [magjac/discourse-d3-graphviz#44]
systematic reproduction sequence, happens in both Chrome and Firefox
1. Copy paste following empty text in post
```
[dot]
[code]

[/code]
[/dot]
```
I think, from there onward, the preview engine is broken, to prove that in two steps 
2. copy paste the dot graph inside the previously pasted blocks
```
digraph G {
node [shape=rect];

subgraph cluster_0 {
style=filled;
color=lightgrey;
node [style=filled,color=white];
a0 -> a1 -> a2 -> a3;
label = "Hello";
}

subgraph cluster_1 {
node [style=filled];
b0 -> b1 -> b2 -> b3;
label = "World";
color=blue
}

start -> a0;
start -> b0;
a1 -> b3;
b2 -> a3;
a3 -> a0;
a3 -> end;
b3 -> end;

start [shape=Mdiamond];
end [shape=Msquare];
}
```

nothing appears on the preview, now last step to show that it has nothing to do with what entered, without touching the edited content, open the middle mouse click on the post page link to 

3. open the same post page in a new browser window : The preview appears correctly

So a workaround until this is solved is 

- Do not type your graph step by step by hand on the post edit with preview window, unless you're aware of the issue and not care about the preview
- do not create an empty graph items
- copy paste the whole characters at once in the edit window [dot][code]graph_text[/code][/dot]

examples :
browser page in a broken state
![image](https://user-images.githubusercontent.com/1510763/84375731-4bbe2d00-abe0-11ea-8d96-fd7d3ac5f43a.png)

new browser window
![image](https://user-images.githubusercontent.com/1510763/84375857-701a0980-abe0-11ea-8514-2dec1b4933cd.png)

- reproduced on : Firefox 77.0.1 (64-bit) / Chrome Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by magjac** [comment]
I can confirm this. For me it happens as soon as you start editing anything. In the console you can see:

`NotFoundError: Node.removeChild: The node to be removed is not a child of this node`

**Comment by wassfila** [comment]
I confirm, all of the tests I reproduced it with are now passing
